/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import main.Shop;

/**
 *
 * @author elyas
 */
public class ShopView extends javax.swing.JFrame implements ActionListener, KeyListener {

    private Shop shop;

    public ShopView() {
        initComponents();
        this.setLocationRelativeTo(null);
        shop = new Shop();
        this.addKeyListener(this);
        this.setFocusable(true);
        // Registro de listeners 
        btnCash.addActionListener(this);
        btnAddProduct.addActionListener(this);
        btnAddStock.addActionListener(this);
        btnDeleteProduct.addActionListener(this);
        btnExport.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCash = new javax.swing.JButton();
        btnAddStock = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCash.setText("1. Contar Caja");

        btnAddStock.setText("3. Añadir Stock");

        btnAddProduct.setText("2. Añadir Producto");

        btnDeleteProduct.setText("4. Eliminar Producto");

        jLabel1.setText("seleccione o pulse una opción:");

        btnExport.setText("Exportar Ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(btnCash, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(btnAddStock, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCash, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnExport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void openCashView() {
        new CashView(this, true, shop).setVisible(true);
    }

    public void openProductView(int option) {
        // 'option' indica a ProductView qué debe hacer (añadir, stock o borrar)
        new ProductView(this, true, shop, option).setVisible(true);
    }

    // --- MANEJO DE EVENTOS DE ACCIÓN (BOTONES) ---
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnCash) {
            openCashView();
        } else if (e.getSource() == btnAddProduct) {
            openProductView(2);
        } else if (e.getSource() == btnAddStock) {
            openProductView(3);
        } else if (e.getSource() == btnDeleteProduct) {
            openProductView(9);
        } else if (e.getSource() == btnExport) {
            handleExport();
        }
        this.requestFocus();
    }

    // --- MANEJO DE EVENTOS DE TECLADO ---
    @Override
    public void keyPressed(KeyEvent e) {
        int k = e.getKeyCode(); // Requisito 3.f [cite: 169]
        if (k == KeyEvent.VK_1) {
            openCashView();
        } else if (k == KeyEvent.VK_2) {
            openProductView(2);
        } else if (k == KeyEvent.VK_3) {
            openProductView(3);
        } else if (k == KeyEvent.VK_9) {
            openProductView(9);
        } else if (k == KeyEvent.VK_7 || k == KeyEvent.VK_NUMPAD7) {
            handleExport(); 
        }
    }

    private void handleExport() {
        int r = JOptionPane.showConfirmDialog(this, "¿Desea exportar las ventas?"); // [cite: 14, 148]
        if (r == JOptionPane.YES_OPTION) {
            shop.writeSales();
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new ShopView().setVisible(true));
    }

    /**
     * Punto de entrada principal (para pruebas directas de ShopView)
     */
}
